### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ghost** [voidpp/PCA9685-driver#1]
If I run the setup (`pip install PCA9685-driver`) the following error occures:

    pi@raspberrypi:~/tmp $ pip install PCA9685-driver
    Collecting PCA9685-driver
    Downloading PCA9685-driver-1.1.0.tar.gz
    Collecting smbus-cffi==0.5.1 (from PCA9685-driver)
    Downloading smbus-cffi-0.5.1.tar.gz
        Complete output from command python setup.py egg_info:
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
        #include <Python.h>
                            ^
        compilation terminated.
        Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-59NF29/smbus-cffi/setup.py", line 48, in <module>
            'Topic :: System :: Hardware',
        File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
            _setup_distribution = dist = klass(attrs)
        File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__
            self.fetch_build_eggs(attrs['setup_requires'])
        File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 377, in fetch_build_eggs
            replace_conflicting=True,
        File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 852, in resolve
            dist = best[req.key] = env.best_match(req, ws, installer)
        File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1124, in best_match
            return self.obtain(req, installer)
        File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1136, in obtain
            return installer(requirement)
        File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 445, in fetch_build_egg
            return cmd.easy_install(req)
        File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 673, in easy_install
            return self.install_item(spec, dist.location, tmpdir, deps)
        File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 699, in install_item
            dists = self.install_eggs(spec, download, tmpdir)
        File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 880, in install_eggs
            return self.build_and_install(setup_script, setup_base)
        File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
            self.run_setup(setup_script, setup_base, args)
        File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1107, in run_setup
            raise DistutilsError("Setup script exited with %s" % (v.args[0],))
        distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-59NF29/smbus-cffi/

How do I fix the problem?
It only occures on my Raspberry. On my main PC pip works fine.
Running pip as root doesn't change anything.

**Comment by voidpp** [comment]
You must install `libffi-dev`

`apt-get install libffi-dev`

**Comment by ghost** [comment]
This didn't solve the problem 😞

**Comment by voidpp** [comment]
Are the python developer packages installed?
If not: `sudo apt-get install python-dev` (in case of python2)

**Comment by ghost** [comment]
It works.
The tool is awesome!
